package com.rest.gui.uas;

import config.conn;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rsstst
 */
public class checkout extends javax.swing.JFrame {
    
    private DefaultTableModel model_item;
    private String query;
    Connection connect = conn.getConnection();
    
    /**
     * Creates new form main
     */
    public checkout() {
        initComponents();
        tampilData();
        String date = LocalDate.now().toString();
        coDate.setText(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cartAkun = new javax.swing.JPanel();
        tabelPanel2 = new javax.swing.JPanel();
        checkoutBtn = new javax.swing.JButton();
        kembaliChkBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chkTable = new javax.swing.JTable();
        refreshAkunBtn = new javax.swing.JButton();
        panelCO = new javax.swing.JPanel();
        coBrand = new javax.swing.JLabel();
        coSubhead = new javax.swing.JLabel();
        coDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cartAkun.setBackground(new java.awt.Color(255, 102, 102));
        cartAkun.setToolTipText("");

        javax.swing.GroupLayout cartAkunLayout = new javax.swing.GroupLayout(cartAkun);
        cartAkun.setLayout(cartAkunLayout);
        cartAkunLayout.setHorizontalGroup(
            cartAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cartAkunLayout.setVerticalGroup(
            cartAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        tabelPanel2.setLayout(new java.awt.GridBagLayout());

        checkoutBtn.setText("Konfirmasi");
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        tabelPanel2.add(checkoutBtn, gridBagConstraints);

        kembaliChkBtn.setText("Kembali");
        kembaliChkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliChkBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        tabelPanel2.add(kembaliChkBtn, gridBagConstraints);

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });
        tabelPanel2.add(hapusBtn, new java.awt.GridBagConstraints());

        chkTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Barang", "Jumlah", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(chkTable);
        if (chkTable.getColumnModel().getColumnCount() > 0) {
            chkTable.getColumnModel().getColumn(0).setResizable(false);
            chkTable.getColumnModel().getColumn(1).setResizable(false);
            chkTable.getColumnModel().getColumn(2).setResizable(false);
            chkTable.getColumnModel().getColumn(3).setResizable(false);
        }

        refreshAkunBtn.setIcon(new javax.swing.ImageIcon("D:\\ref.png")); // NOI18N
        refreshAkunBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshAkunBtnActionPerformed(evt);
            }
        });

        coBrand.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        coBrand.setText("iSeller");

        coSubhead.setText("Selamat datang! Selamat berbelanja~");

        coDate.setText("Tanggal");

        javax.swing.GroupLayout panelCOLayout = new javax.swing.GroupLayout(panelCO);
        panelCO.setLayout(panelCOLayout);
        panelCOLayout.setHorizontalGroup(
            panelCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coSubhead, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(coBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(coDate, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCOLayout.setVerticalGroup(
            panelCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coBrand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coSubhead, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(coDate))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cartAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshAkunBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tabelPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cartAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshAkunBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tampilData(){
        model_item = new DefaultTableModel();
        model_item.addColumn("ID");
        model_item.addColumn("Nama Barang");
        model_item.addColumn("Jumlah");
        model_item.addColumn("Harga");
        chkTable.setModel(model_item);

        try {
            DecimalFormat Decformat = new DecimalFormat("#.##");
            Decformat.setGroupingUsed(true);
            Decformat.setGroupingSize(3);
            java.sql.Statement stmt = connect.createStatement();
            query = "SELECT * FROM checkout";
            java.sql.ResultSet rs = stmt.executeQuery(query);
            while (rs.next()){
                int harga = rs.getInt("hargaCO");
                model_item.addRow(new Object[]{
                    rs.getString("idCO"),
                    rs.getString("namaCO"),
                    rs.getString("jumlahCO"),
                    Decformat.format(harga)
                });
            }  
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }}
    
    private void refreshAkunBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshAkunBtnActionPerformed
        tampilData();
    }//GEN-LAST:event_refreshAkunBtnActionPerformed

    private void kembaliChkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliChkBtnActionPerformed
        mainframe main = new mainframe();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_kembaliChkBtnActionPerformed

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed

        int answ = JOptionPane.showConfirmDialog(this, "Apakah anda yakin dengan item yang ingin dibeli?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_checkoutBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
       try {
           int rIndex = chkTable.getSelectedRow();
           int cIndex = 0;
           Object obj = chkTable.getValueAt(rIndex, cIndex);
           
           java.sql.Statement stmt = connect.createStatement();
           query = "DELETE FROM checkout WHERE idCO = " + obj;
           stmt.execute(query);
           System.out.println("Data dihapus");
       } catch (Exception e) {
           System.out.println(e.getMessage());
       }

    }//GEN-LAST:event_hapusBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cartAkun;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JTable chkTable;
    private javax.swing.JLabel coBrand;
    private javax.swing.JLabel coDate;
    public javax.swing.JLabel coSubhead;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembaliChkBtn;
    private javax.swing.JPanel panelCO;
    private javax.swing.JButton refreshAkunBtn;
    private javax.swing.JPanel tabelPanel2;
    // End of variables declaration//GEN-END:variables
}
