package com.rest.gui.uas;

import config.conn;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rsstst
 */
public class item extends javax.swing.JFrame {
    
    private DefaultTableModel model_item;
    private String query;
    Connection connect = conn.getConnection();
    
    /**
     * Creates new form main
     */
    public item() {
        initComponents();
        tampilData();
        String date = LocalDate.now().toString();
        itemDate.setText(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cartItem = new javax.swing.JPanel();
        tabelPanel1 = new javax.swing.JPanel();
        tambahItemBtn = new javax.swing.JButton();
        checkoutItemBtn = new javax.swing.JButton();
        kembaliItemBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        refreshItemBtn = new javax.swing.JButton();
        panelItem = new javax.swing.JPanel();
        itemBrand = new javax.swing.JLabel();
        itemSubhead = new javax.swing.JLabel();
        itemDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cartItem.setBackground(new java.awt.Color(255, 102, 102));
        cartItem.setToolTipText("");

        javax.swing.GroupLayout cartItemLayout = new javax.swing.GroupLayout(cartItem);
        cartItem.setLayout(cartItemLayout);
        cartItemLayout.setHorizontalGroup(
            cartItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cartItemLayout.setVerticalGroup(
            cartItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        tabelPanel1.setLayout(new java.awt.GridBagLayout());

        tambahItemBtn.setText("Tambah Item");
        tambahItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahItemBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        tabelPanel1.add(tambahItemBtn, gridBagConstraints);

        checkoutItemBtn.setText("Checkout");
        checkoutItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutItemBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        tabelPanel1.add(checkoutItemBtn, gridBagConstraints);

        kembaliItemBtn.setText("Kembali");
        kembaliItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliItemBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        tabelPanel1.add(kembaliItemBtn, gridBagConstraints);

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Game", "Nama Item", "Stok", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(itemTable);
        if (itemTable.getColumnModel().getColumnCount() > 0) {
            itemTable.getColumnModel().getColumn(0).setResizable(false);
            itemTable.getColumnModel().getColumn(1).setResizable(false);
            itemTable.getColumnModel().getColumn(2).setResizable(false);
            itemTable.getColumnModel().getColumn(3).setResizable(false);
            itemTable.getColumnModel().getColumn(4).setResizable(false);
        }

        refreshItemBtn.setIcon(new javax.swing.ImageIcon("D:\\ref.png")); // NOI18N
        refreshItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshItemBtnActionPerformed(evt);
            }
        });

        itemBrand.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        itemBrand.setText("iSeller");

        itemSubhead.setText("Selamat datang! Selamat berbelanja~");

        itemDate.setText("Tanggal");

        javax.swing.GroupLayout panelItemLayout = new javax.swing.GroupLayout(panelItem);
        panelItem.setLayout(panelItemLayout);
        panelItemLayout.setHorizontalGroup(
            panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemSubhead, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(itemBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(itemDate, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelItemLayout.setVerticalGroup(
            panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemBrand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemSubhead, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(itemDate))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cartItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tabelPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cartItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tampilData(){
        model_item = new DefaultTableModel();
        model_item.addColumn("ID");
        model_item.addColumn("Game");
        model_item.addColumn("Nama Item");
        model_item.addColumn("Stok");
        model_item.addColumn("Harga");
        itemTable.setModel(model_item);

        try {
            DecimalFormat Decformat = new DecimalFormat("#.##");
            Decformat.setGroupingUsed(true);
            Decformat.setGroupingSize(3);
            java.sql.Statement stmt = connect.createStatement();
            query = "SELECT * FROM stok_item";
            java.sql.ResultSet rs = stmt.executeQuery(query);
            while (rs.next()){
                int harga = rs.getInt("harga_barang");
                model_item.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("game"),
                    rs.getString("nama_barang"),
                    rs.getString("jumlah_barang"),
                    Decformat.format(harga)
                });
            }  
    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }}
    
    private void refreshItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshItemBtnActionPerformed
        tampilData();
    }//GEN-LAST:event_refreshItemBtnActionPerformed

    private void kembaliItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliItemBtnActionPerformed
        mainframe main = new mainframe();
        main.setVisible(true);
        main.pack();
        main.setLocationRelativeTo(null);
        main.setDefaultCloseOperation(EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_kembaliItemBtnActionPerformed

    private void checkoutItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutItemBtnActionPerformed
        checkout chk = new checkout();
        chk.setVisible(true);
        chk.pack();
        chk.setLocationRelativeTo(null);
        chk.setDefaultCloseOperation(EXIT_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_checkoutItemBtnActionPerformed

    private void tambahItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahItemBtnActionPerformed

        try {
            int rIndex = itemTable.getSelectedRow();
            int cIndex = 0;
            Object obj = itemTable.getValueAt(rIndex, cIndex);
            System.out.println(obj);
            
            java.sql.Statement stmt = connect.createStatement();
            query = "INSERT INTO checkout (idCO, namaCO, jumlahCO, hargaCO)\nSELECT id, nama_barang, jumlah_barang, harga_barang FROM stok_item WHERE id = " + obj;
            stmt.execute(query);
            JOptionPane.showMessageDialog(this, "Item telah ditambahkan");
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tambahItemBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cartItem;
    private javax.swing.JButton checkoutItemBtn;
    private javax.swing.JLabel itemBrand;
    private javax.swing.JLabel itemDate;
    public javax.swing.JLabel itemSubhead;
    private javax.swing.JTable itemTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembaliItemBtn;
    private javax.swing.JPanel panelItem;
    public javax.swing.JButton refreshItemBtn;
    private javax.swing.JPanel tabelPanel1;
    private javax.swing.JButton tambahItemBtn;
    // End of variables declaration//GEN-END:variables
}
